name: Build Installers

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  APP_NAME: BicycleSharing
  MAIN_CLASS: org.example.bicyclesharing.Launcher

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Show target
        shell: powershell
        run: dir target

      - name: Detect JAR
        shell: powershell
        run: |
          $jar = Get-ChildItem target/*.jar | Where-Object { $_.Name -notlike "*sources*" } | Select-Object -First 1
          echo "JAR_NAME=$($jar.Name)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Clean version
        shell: powershell
        run: |
          $ver = "${{ github.ref_name }}" -replace "^v", ""
          echo "VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create runtime (jlink)
        shell: powershell
        run: |
          jlink `
            --add-modules java.base,java.desktop `
            --output runtime

      - name: Build MSI
        shell: powershell
        run: |
          jpackage `
            --type msi `
            --name "${{ env.APP_NAME }}" `
            --app-version "${{ env.VERSION }}" `
            --vendor "Serhii" `
            --input target `
            --main-jar "${{ env.JAR_NAME }}" `
            --main-class "${{ env.MAIN_CLASS }}" `
            --runtime-image runtime `
            --dest dist `
            --win-dir-chooser `
            --win-menu `
            --win-shortcut

      - name: Rename
        shell: powershell
        run: |
          $file = Get-ChildItem dist/*.msi | Select-Object -First 1
          Move-Item $file.FullName "dist/${{ env.APP_NAME }}-Windows.msi"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/*.msi


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Detect JAR
        run: |
          JAR=$(ls target/*.jar | grep -v sources | head -n 1)
          echo "JAR_NAME=$(basename $JAR)" >> $GITHUB_ENV

      - name: Clean version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Create runtime (jlink)
        run: |
          jlink \
            --add-modules java.base,java.desktop \
            --output runtime

      - name: Build DEB
        run: |
          jpackage \
            --type deb \
            --name "${{ env.APP_NAME }}" \
            --app-version "${{ env.VERSION }}" \
            --vendor "Serhii" \
            --input target \
            --main-jar "${{ env.JAR_NAME }}" \
            --main-class "${{ env.MAIN_CLASS }}" \
            --runtime-image runtime \
            --dest dist \
            --linux-shortcut

      - name: Rename
        run: mv dist/*.deb dist/${{ env.APP_NAME }}-Linux.deb

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: dist/*.deb


  build-macos:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Detect JAR
        run: |
          JAR=$(ls target/*.jar | grep -v sources | head -n 1)
          echo "JAR_NAME=$(basename $JAR)" >> $GITHUB_ENV

      - name: Clean version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Create runtime (jlink)
        run: |
          jlink \
            --add-modules java.base,java.desktop \
            --output runtime

      - name: Build DMG
        run: |
          jpackage \
            --type dmg \
            --name "${{ env.APP_NAME }}" \
            --app-version "${{ env.VERSION }}" \
            --vendor "Serhii" \
            --input target \
            --main-jar "${{ env.JAR_NAME }}" \
            --main-class "${{ env.MAIN_CLASS }}" \
            --runtime-image runtime \
            --dest dist

      - name: Rename
        run: mv dist/*.dmg dist/${{ env.APP_NAME }}-macOS.dmg

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: dist/*.dmg


  publish-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true

      - name: Show files
        run: ls -la release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.APP_NAME }} ${GITHUB_REF_NAME#v}"
          generate_release_notes: true
          files: release/*